# Generated by Django 4.0.6 on 2022-07-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('ses_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='ZoneCords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapt', models.FloatField()),
                ('long', models.FloatField()),
                ('ses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
            options={
                'verbose_name': 'ZoneCord',
                'verbose_name_plural': 'ZoneCords',
            },
        ),
        migrations.CreateModel(
            name='UserCords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapt', models.FloatField()),
                ('long', models.FloatField()),
                ('ses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='TargetCords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapt', models.FloatField()),
                ('long', models.FloatField()),
                ('ses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
            options={
                'verbose_name': 'TargetCord',
                'verbose_name_plural': 'TargetCords',
            },
        ),
    ]
